### ISSUE TITLE
Support default values

### ISSUE THREAD

**Issue by edenman** [ansman/kotshi#5]
I know this is called out as not-yet-supported in the README, but I wanted some way to get notified when this support was added, so filing this :)

**Comment by ansman** [comment]
Current suggestion involved annotating a property/function with an annotation to indicate it can provide default values.

One tricky bit to solve with this approach is generics since multiple functions might match the same type. The most specific should then be chosen but it might be multiple that are as specific.

My options so far seems to be:
- Only allow generic default providers without a bound
- If multiple could be used, throw an exception

In reality I expect most to either have no generics (`fun provideDefaultString()`)  or with no bounds (`fun <T> provideDefaultList()`).

**Comment by ansman** [comment]
There is also a couple of additional questions:
- Should there be an optional for enabling a default for all non nullable primitive types automatically?
- Should `null` and an absent key be treated differently?

**Comment by ansman** [comment]
@edenman There is now an open PR for implementing default values. If you have time I would appreciate it if you could review it and give feedback on both the api design as well as the implementation.

**Comment by edenman** [comment]
@ansman I think I would've been perfectly happy with `@UseDefaultValue("foo") val bar: String` as an API.  Not sure if being able to supply default values from a function is worth the added complexity, but obviously up to you.

**Comment by ansman** [comment]
@edenman That only works for primitive types. Perhaps it should be possible to do this for the primitive types too. For example `@JsonDefaultString("foo")`

**Comment by edenman** [comment]
Yeah, the only default values I care about are for primitive types.  Seems a bit overcomplicated to allow default values for complex objects, but again, that may just be because of my particular style of building client APIs.

**Comment by digitalbuddha** [comment]
Likewise I'd much prefer a simple api for primitives only rather than a bit more boilerplate and object support

**Comment by ansman** [comment]
There we go, it's now implemented for the types that support it.
