### ISSUE TITLE
Implement JsonAdapter.toString.

### ISSUE THREAD

**Issue by NightlyNexus** [ansman/kotshi#50]
Would you consider a PR to implement toString() on the generated adapters?
of the same format as other JsonAdapters (https://github.com/square/moshi/blob/5b194964a99a89f94df1ae0ace881dec7c43679d/kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt#L120).

**Comment by JakeWharton** [comment]
An easy way to mitigate the method count impact (referenced in the other issue) is by putting an `abstract` adapter in the runtime library which takes a `String` in its constructor that is returned from its `final toString()` method. The key trick here is that this adds a fixed number of methods (2) rather than 1 per adapter.

**Comment by NightlyNexus** [comment]
Yeah, it's worth optimizing for generated code.

**Comment by ansman** [comment]
That sounds like a good idea. What should the toString method return in order to be useful?

**Comment by NightlyNexus** [comment]
`JsonAdapter($type)` or `JsonAdapter($type).nullSafe()` if you'd rather not use the null-safe adapter.

**Comment by ansman** [comment]
Sounds like a good idea then. I'm guessing we should name it `KotshiJsonAdapter($type)` or something like that instead which would indicate both null safe and that is generated by Kotshi. Having `.nullSafe()` appended seems like a bad idea since it could be confused with actually calling `nullSafe` on it.

**Comment by JakeWharton** [comment]
:+1:

**Comment by ansman** [comment]
I implemented this in #52, take a look. I'm not 100% sure about the names. Also, would be better to just pass the type name to the super class and let `toString` build the final string? I guess it would be slower in runtime but it would require less space in the class files since the string constants are smaller?

**Comment by JakeWharton** [comment]
I think it's better to do at compile time. The strings will compress well.

**Comment by ansman** [comment]
That's what I figured. This could be changed later if someone decides to benchmark it.
